DROP TABLE 'todo';

CREATE TABLE wood (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    subject VARCHAR(255) NOT NULL,
    date VARCHAR(10) NOT NULL
    task VARCHAR(255) NOT NULL
);BIGINT PRIMARY